name: Release-pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: "false"
          onlyLastTag: "true"
          stripGeneratorNotice: "true"
          issuesWoLabels: "true"
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Branch
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=BRANCH_NAME::$branch"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build Carrier
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: |
          make build-all-small
      - name: Create CHECKSUMS
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: ( cd dist ; sha256sum -b carrier* > SHA256SUM.txt )
      - name: Release Carrier
        uses: softprops/action-gh-release@v1
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        with:
          files: ./dist/*
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
